services:
  # 1. Base de données PostgreSQL
  db:
    image: postgres:17-alpine
    container_name: cif_postgres_db
    environment:
      POSTGRES_USER: cif_user
      POSTGRES_PASSWORD: cif_password
      POSTGRES_DB: cif_microcredit
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
