# Configuration de la base de données PostgreSQL (celle de notre Docker)
spring.datasource.url=jdbc:postgresql://localhost:5433/cif_microcredit
spring.datasource.username=cif_user
spring.datasource.password=cif_password

# JPA / Hibernate : Pour créer les tables automatiquement
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Nom de notre application
spring.application.name=API Scoring Microcredit
