# Configuration de la base de données PostgreSQL (locale ou cloud via variables)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5434/cif_microcredit}
spring.datasource.username=${DB_USER:cif_user}
spring.datasource.password=${DB_PASSWORD:cif_password}

# Port dynamique (indispensable pour Render.com)
server.port=${PORT:8080}

# JPA / Hibernate : Pour créer les tables automatiquement
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Nom de notre application
spring.application.name=API Scoring Microcredit
